
server.port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/academia?createDatabaseIfNotExist=True
    username: danielle
    password: D@n11306
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace